### PR TITLE
FileSystem cache changes

### PR DESCRIPTION
**Pull request by peter-r-g**
This PR makes a couple of changes when interacting with the icon cache while maintaining backward compatibility.

1. Uses async IO operations where available instead of blocking ones.
2. Allows the user to change the file system used for caching icons.
  * Can be set in code or in Razor.
  * Defaults to the iconify directory in FileSystem.Data as was default before.
  * The cache is written to the root directory of the file system provided.

### Known Issues
As mentioned in a4264d97387dd9addd77835900988ff9b1c78df1 S&box doesn't seem to call SetPropertyObject and instead ToStrings everything and passes it through SetProperty instead. Because of this you cannot actually set the cache in Razor right now.

### CODE REVIEW

**Review by xezno — CHANGES_REQUESTED** [review]
Thanks for this - the async IO operations are a good idea and are a good change!

I think we should do things like the FileSystem cache differently - using a config file somewhere (inside the game's filesystem maybe) that we can then expand on later; I don't think people are going to want to do this stuff per-element, so it doesn't make much sense to me to specify it every time you use an element.

**Comment by peter-r-g** [comment]
> I think we should do things like the FileSystem cache differently (...) I don't think people are going to want to do this stuff per-element, so it doesn't make much sense to me to specify it every time you use an element.

Agreed, I don't think doing this configuration through a file is a good alternative though. I think it would be best to set this stuff up in code. Perhaps creating a central class would suffice. Something like so:

```cs
public class IconifyOptions
{
    public static IconifyOptions Current { get; set; } = new();

    public BaseFileSystem CacheFileSystem { get; set; } = FileSystem.Data;

    public IconifyOptions WithCacheFileSystem( BaseFileSystem fs )
    {
        CacheFileSystem = fs;
        return this;
    }
}
```
Then the library code can access said options through `IconifyOptions.Current` and users can create their options like so:
```cs
IconifyOptions.Current = new IconifyOptions()
    .WithCacheFileSystem( FileSystem.OrganizationData );
```

**Comment by xezno** [comment]
Yeah that makes more sense to me. Ideally we should probably expose something in s&box that lets you config a library somewhere, like in the project settings itself, but we don't have that right now - so setting it up in code works for me

**Comment by peter-r-g** [comment]
All good to go now

**Review by xezno — APPROVED** [review]
LGTM, thank you <3

**Pull request merged**
